server:
  port: 9999
  servlet:
    context-path: /study
wifi:
  server: http://221.7.105.6:1002/
  task:
    pull: 0 0 0/12 * * ?
    login: 0 0 0/12 * * ?
  enable: false
  username: admin
  password: adminkst
  env: linux  # env: linux/windows
  windows:
    path: E:\chromedriver\chromedriver.exe
  linux:
    linuxDriverUrl: http://localhost:9515



