server:
  port: 17777
  servlet:
    context-path: /cdfyshow
spring:
  datasource:
    druid:
      url: jdbc:mysql://172.16.9.19:3306/cdfy_show?characterEncoding=utf-8
      username: root
      password: wisesoft
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

images:
  url: http://124.161.16.163:8099/cdfyimages/
  userPath: user
  scenicPath: scenic